# Generated by Django 5.1.1 on 2024-11-09 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='doc_chunk_doc_page_idx',
        ),
        migrations.RemoveIndex(
            model_name='governancedocument',
            name='gov_doc_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='processinglog',
            name='proc_log_timestamp_idx',
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance_analysis.governancedocument'),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance_analysis.governancedocument'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='governancedocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
