# Generated by Django 5.1.1 on 2024-11-09 19:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance_analysis', '0002_remove_documentchunk_doc_chunk_doc_page_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='governancedocument',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='governancedocument',
            name='mime_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='governance_analysis.governancedocument'),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='page_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bestpractice',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='governance_analysis.governancedocument'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='governancedocument',
            name='filename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='governancedocument',
            name='pinata_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='governancedocument',
            name='processed_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='governancedocument',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='stage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='bestpractice',
            index=models.Index(fields=['document', 'page_number'], name='best_practi_documen_9bdaea_idx'),
        ),
        migrations.AddIndex(
            model_name='bestpractice',
            index=models.Index(fields=['confidence_score'], name='best_practi_confide_4326b0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'page_number', 'position'], name='document_ch_documen_5b7bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['chunk_size'], name='document_ch_chunk_s_858c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['upload_date'], name='governance__upload__f673fb_idx'),
        ),
        migrations.AddIndex(
            model_name='governancedocument',
            index=models.Index(fields=['processed_status'], name='governance__process_3dfb42_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['document_id', 'timestamp'], name='processing__documen_f0d202_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['stage', 'status'], name='processing__stage_018654_idx'),
        ),
    ]
