# Generated by Django 5.1.1 on 2024-11-09 23:30

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance_analysis', '0003_bestpractice_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpractice',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
