# Generated by Django 5.1.1 on 2024-11-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance_analysis', '0004_alter_bestpractice_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('frequency', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_themes',
                'ordering': ['-frequency'],
                'indexes': [models.Index(fields=['frequency'], name='shared_them_frequen_6b331f_idx'), models.Index(fields=['name'], name='shared_them_name_9074d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_strength', models.FloatField(default=0.0, help_text='Calculated based on number of shared themes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='governance_analysis.governancedocument')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='governance_analysis.governancedocument')),
                ('shared_themes', models.ManyToManyField(to='governance_analysis.sharedtheme')),
            ],
            options={
                'db_table': 'document_relationships',
                'indexes': [models.Index(fields=['relationship_strength'], name='document_re_relatio_84b12d_idx')],
                'unique_together': {('source_document', 'target_document')},
            },
        ),
        migrations.CreateModel(
            name='ThemeOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_excerpt', models.TextField(help_text='Relevant text excerpt where theme appears')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance_analysis.documentchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance_analysis.governancedocument')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance_analysis.sharedtheme')),
            ],
            options={
                'db_table': 'theme_occurrences',
                'indexes': [models.Index(fields=['theme', 'document'], name='theme_occur_theme_i_1d19e1_idx'), models.Index(fields=['confidence_score'], name='theme_occur_confide_a8b121_idx')],
            },
        ),
    ]
