# Generated by Django 5.1.1 on 2024-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance_analysis', '0005_sharedtheme_documentrelationship_themeoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpractice',
            name='is_best_practice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='bestpractice',
            index=models.Index(fields=['is_best_practice'], name='best_practi_is_best_c40fd4_idx'),
        ),
    ]
